"""
Generate a brief summary PDF for the C15 esophageal cancer analysis.
Output: results/C15_Esophageal_Cancer_Summary.pdf
"""
import sys
from pathlib import Path
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.patches import FancyBboxPatch
import matplotlib.image as mpimg
import warnings
warnings.filterwarnings("ignore")

BASE    = Path(__file__).parent.parent
RES02   = BASE / "results/02_descriptive"
RES03   = BASE / "results/03_survival"
RES04   = BASE / "results/04_deep_learning"
OUT_PDF = BASE / "results/C15_Esophageal_Cancer_Summary.pdf"

TITLE_COLOR  = "#1a3a5c"
ACCENT_COLOR = "#2e7fbf"
BG_LIGHT     = "#f4f8fc"
GRAY         = "#555555"

def add_header(fig, title, subtitle=""):
    fig.patch.set_facecolor("white")
    fig.text(0.5, 0.97, title, ha="center", va="top", fontsize=16,
             fontweight="bold", color=TITLE_COLOR)
    if subtitle:
        fig.text(0.5, 0.93, subtitle, ha="center", va="top", fontsize=10, color=GRAY)

def add_footer(fig, page_num, total):
    fig.text(0.5, 0.01, f"Taiwan Cancer Registry 2006–2020  |  C15 Esophageal Cancer  |  Page {page_num}/{total}",
             ha="center", va="bottom", fontsize=7, color=GRAY)
    fig.text(0.98, 0.01, "Generated by Claude Code", ha="right", va="bottom", fontsize=7, color=GRAY)

def stat_box(ax, label, value, sub="", bg=BG_LIGHT):
    ax.set_facecolor(bg)
    ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    ax.axis("off")
    ax.text(0.5, 0.62, value, ha="center", va="center", fontsize=20,
            fontweight="bold", color=ACCENT_COLOR)
    ax.text(0.5, 0.28, label, ha="center", va="center", fontsize=9,
            fontweight="bold", color=TITLE_COLOR)
    if sub:
        ax.text(0.5, 0.10, sub, ha="center", va="center", fontsize=7.5, color=GRAY)
    rect = FancyBboxPatch((0.03, 0.03), 0.94, 0.94, boxstyle="round,pad=0.02",
                          linewidth=1.2, edgecolor=ACCENT_COLOR, facecolor=bg)
    ax.add_patch(rect)

def load_image(path):
    try:
        return mpimg.imread(str(path))
    except Exception:
        return None

with PdfPages(OUT_PDF) as pdf:

    # ── PAGE 1: Cover + Key Statistics ────────────────────────────────────────
    fig = plt.figure(figsize=(8.27, 11.69))  # A4
    add_footer(fig, 1, 5)

    # Title block
    ax_title = fig.add_axes([0.05, 0.78, 0.90, 0.18])
    ax_title.set_facecolor(TITLE_COLOR)
    ax_title.axis("off")
    ax_title.text(0.5, 0.65, "Esophageal Cancer (C15)", ha="center", va="center",
                  fontsize=22, fontweight="bold", color="white")
    ax_title.text(0.5, 0.28, "Taiwan Cancer Registry 2006–2020  |  Single-Center Analysis",
                  ha="center", va="center", fontsize=12, color="#aaccee")

    # Key stats row
    stats = [
        ("2,367", "Total Cases", "2006–2020"),
        ("57 yrs", "Median Age", "IQR 50–64"),
        ("94.5%", "Male", "M:F = 17:1"),
        ("85.4%", "SCC", "Squamous cell"),
        ("77.3%", "Mortality", "1,832 events"),
    ]
    for i, (val, lbl, sub) in enumerate(stats):
        ax = fig.add_axes([0.04 + i*0.192, 0.62, 0.17, 0.13])
        stat_box(ax, lbl, val, sub)

    # Table 1 summary
    t1 = pd.read_csv(RES02 / "table1_demographics.csv")
    ax_t = fig.add_axes([0.05, 0.08, 0.88, 0.51])
    ax_t.axis("off")
    ax_t.text(0, 1.0, "Table 1 — Clinical Summary", fontsize=12, fontweight="bold",
              color=TITLE_COLOR, va="top", transform=ax_t.transAxes)

    # Select key rows
    keep = [r for _, r in t1.iterrows()
            if not r["Variable"].startswith("---") and r["Variable"] != "n"]
    disp = pd.DataFrame(keep)[["Variable","Value"]].head(35)
    disp["Variable"] = disp["Variable"].str.replace("_", " ")

    tbl = ax_t.table(
        cellText=disp.values,
        colLabels=["Variable", "Value (n, %)"],
        loc="upper center", cellLoc="left",
        bbox=[0, 0, 1, 0.96]
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    for (r, c), cell in tbl.get_celld().items():
        cell.set_edgecolor("#dddddd")
        if r == 0:
            cell.set_facecolor(ACCENT_COLOR)
            cell.set_text_props(color="white", fontweight="bold")
        elif r % 2 == 0:
            cell.set_facecolor("#eef4fb")
        else:
            cell.set_facecolor("white")

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # ── PAGE 2: Descriptive Figures ────────────────────────────────────────────
    fig = plt.figure(figsize=(8.27, 11.69))
    add_header(fig, "Descriptive Analysis", "Clinical Signatures")
    add_footer(fig, 2, 5)

    imgs = [
        (RES02 / "fig_incidence_trend.png",   [0.05, 0.70, 0.90, 0.20], "Annual Incidence Trend"),
        (RES02 / "fig_age_sex.png",            [0.05, 0.46, 0.90, 0.22], "Age & Sex Distribution"),
        (RES02 / "fig_histology_stage.png",    [0.05, 0.23, 0.90, 0.21], "Histology & Stage"),
        (RES02 / "fig_subsite_stage.png",      [0.05, 0.02, 0.90, 0.19], "Subsite × Stage Heatmap"),
    ]
    for path, rect, caption in imgs:
        img = load_image(path)
        if img is not None:
            ax = fig.add_axes(rect)
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(caption, fontsize=9, color=GRAY, pad=2)

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # ── PAGE 3: Treatment & Lifestyle ─────────────────────────────────────────
    fig = plt.figure(figsize=(8.27, 11.69))
    add_header(fig, "Treatment Patterns & Lifestyle", "")
    add_footer(fig, 3, 5)

    tx_imgs = [
        (RES02 / "fig_treatment_combinations.png", [0.05, 0.55, 0.90, 0.33], "Treatment Combinations"),
        (RES02 / "fig_treatment_cooccurrence.png", [0.05, 0.27, 0.44, 0.26], "Co-occurrence Matrix"),
        (RES02 / "fig_lifestyle.png",               [0.05, 0.02, 0.90, 0.23], "Lifestyle Factors"),
    ]
    for path, rect, caption in tx_imgs:
        img = load_image(path)
        if img is not None:
            ax = fig.add_axes(rect)
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(caption, fontsize=9, color=GRAY, pad=2)

    # Treatment stats callout
    ax_note = fig.add_axes([0.52, 0.27, 0.43, 0.26])
    ax_note.axis("off")
    ax_note.set_facecolor(BG_LIGHT)
    notes = [
        ("72.2%", "Received radiation therapy"),
        ("72.0%", "Received chemotherapy"),
        ("23.7%", "Received immunotherapy"),
        ("22.9%", "Received targeted therapy"),
        ("22.5%", "Underwent surgery"),
        ("",      ""),
        ("Most common combination:", ""),
        ("Radiation + Chemo (CCRT)", ""),
    ]
    ax_note.text(0.5, 0.97, "Treatment Summary", ha="center", va="top",
                 fontsize=10, fontweight="bold", color=TITLE_COLOR,
                 transform=ax_note.transAxes)
    for j, (val, desc) in enumerate(notes):
        y = 0.82 - j * 0.10
        if val and "%" in val:
            ax_note.text(0.08, y, val, fontsize=11, fontweight="bold",
                         color=ACCENT_COLOR, transform=ax_note.transAxes)
            ax_note.text(0.35, y, desc, fontsize=8, color=GRAY,
                         transform=ax_note.transAxes, va="center")
        elif val:
            ax_note.text(0.08, y, val, fontsize=8, fontweight="bold",
                         color=TITLE_COLOR, transform=ax_note.transAxes)
            ax_note.text(0.08, y - 0.08, desc, fontsize=9, fontweight="bold",
                         color=ACCENT_COLOR, transform=ax_note.transAxes)

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # ── PAGE 4: Survival Analysis ──────────────────────────────────────────────
    fig = plt.figure(figsize=(8.27, 11.69))
    add_header(fig, "Survival Analysis", "Kaplan-Meier & Cox Proportional Hazards")
    add_footer(fig, 4, 5)

    surv_imgs = [
        (RES03 / "km_stage.png",      [0.03, 0.57, 0.48, 0.30], "OS by AJCC Stage"),
        (RES03 / "km_surgery.png",    [0.51, 0.57, 0.48, 0.30], "OS by Surgery"),
        (RES03 / "km_css_stage.png",  [0.03, 0.26, 0.48, 0.29], "Cancer-Specific Survival by Stage"),
        (RES03 / "cox_forest_plot.png",[0.51, 0.26, 0.48, 0.29], "Cox Proportional Hazards"),
    ]
    for path, rect, caption in surv_imgs:
        img = load_image(path)
        if img is not None:
            ax = fig.add_axes(rect)
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(caption, fontsize=9, color=GRAY, pad=2)

    # Cox key findings box
    ax_cox = fig.add_axes([0.03, 0.03, 0.94, 0.21])
    ax_cox.set_facecolor(BG_LIGHT)
    ax_cox.axis("off")
    rect_bg = FancyBboxPatch((0.01, 0.04), 0.98, 0.92, boxstyle="round,pad=0.01",
                             linewidth=1, edgecolor=ACCENT_COLOR, facecolor=BG_LIGHT)
    ax_cox.add_patch(rect_bg)
    ax_cox.text(0.5, 0.88, "Cox Model Key Findings  (Concordance = 0.70, n=2,363)",
                ha="center", va="top", fontsize=10, fontweight="bold",
                color=TITLE_COLOR, transform=ax_cox.transAxes)

    cox_df = pd.read_csv(RES03 / "cox_summary.csv")
    cox_df.columns = ["covariate"] + list(cox_df.columns[1:])
    sig = cox_df[cox_df["p"] < 0.05].copy()
    sig["direction"] = sig["HR"].apply(lambda x: "▲ Higher risk" if x > 1 else "▼ Lower risk")
    sig["HR_fmt"] = sig["HR"].apply(lambda x: f"HR={x:.2f}")

    col_w = 0.30
    for j, (_, row) in enumerate(sig.iterrows()):
        col = j % 3
        rownum = j // 3
        x = 0.02 + col * col_w
        y = 0.68 - rownum * 0.22
        color = "#c0392b" if row["HR"] > 1 else "#27ae60"
        ax_cox.text(x, y, f"• {row['covariate']}", fontsize=8, fontweight="bold",
                    color=TITLE_COLOR, transform=ax_cox.transAxes)
        ax_cox.text(x, y - 0.13, f"  {row['HR_fmt']}  {row['direction']}  p={row['p']:.3f}",
                    fontsize=7.5, color=color, transform=ax_cox.transAxes)

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # ── PAGE 5: Deep Learning Discoveries ─────────────────────────────────────
    fig = plt.figure(figsize=(8.27, 11.69))
    add_header(fig, "Deep Learning Discovery", "Autoencoder · UMAP · k-Means · DeepSurv")
    add_footer(fig, 5, 5)

    dl_imgs = [
        (RES04 / "umap_kmeans_k3.png",            [0.03, 0.62, 0.46, 0.26], "UMAP — k-Means Clusters (k=3)"),
        (RES04 / "umap_stage.png",                 [0.51, 0.62, 0.46, 0.26], "UMAP — AJCC Stage"),
        (RES04 / "km_clusters_k3.png",             [0.03, 0.33, 0.46, 0.27], "KM — Patient Clusters"),
        (RES04 / "deepsurv_feature_importance.png",[0.51, 0.33, 0.46, 0.27], "DeepSurv Feature Importance"),
    ]
    for path, rect, caption in dl_imgs:
        img = load_image(path)
        if img is not None:
            ax = fig.add_axes(rect)
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(caption, fontsize=9, color=GRAY, pad=2)

    # Cluster profiles
    try:
        cp = pd.read_csv(RES04 / "cluster_kmeans_profile.csv")
        ax_cp = fig.add_axes([0.03, 0.02, 0.94, 0.29])
        ax_cp.axis("off")
        ax_cp.text(0, 0.97, "Novel Patient Cluster Profiles (k-Means on Autoencoder Latent Space)",
                   fontsize=10, fontweight="bold", color=TITLE_COLOR,
                   transform=ax_cp.transAxes, va="top")
        rows = [
            ["Cluster", "n", "Median OS\n(months)", "SCC %", "Adenocarcinoma %",
             "Dominant Subsite", "Interpretation"],
        ]
        interp = {
            0: "Adenocarcinoma-enriched\n(overlapping/abdominal)",
            1: "Pure SCC mainstream\n(all subsites)",
            2: "Cervical/upper SCC\n(anatomically distinct)",
        }
        subsite_dom = {0: "Overlapping (53%)", 1: "Overlapping+Abdominal", 2: "Cervical/NOS (77%)"}
        for _, r in cp.iterrows():
            c = int(r["cluster"])
            scc_pct = f"{r.get('mean_hist_SCC', np.nan)*100:.0f}%"
            adc_pct = f"{r.get('mean_hist_Adenocarcinoma', np.nan)*100:.0f}%"
            rows.append([
                f"Cluster {c}", str(int(r["n"])),
                f"{r['median_os_months']:.1f}",
                scc_pct, adc_pct,
                subsite_dom.get(c, "—"),
                interp.get(c, "—")
            ])
        tbl = ax_cp.table(cellText=rows[1:], colLabels=rows[0],
                          loc="upper center", cellLoc="center",
                          bbox=[0, 0, 1, 0.88])
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(7.5)
        for (r2, c2), cell in tbl.get_celld().items():
            cell.set_edgecolor("#dddddd")
            if r2 == 0:
                cell.set_facecolor(ACCENT_COLOR)
                cell.set_text_props(color="white", fontweight="bold")
            elif int(rows[r2][0].split()[-1]) == 0:
                cell.set_facecolor("#fff3e0")
            elif int(rows[r2][0].split()[-1]) == 2:
                cell.set_facecolor("#e8f5e9")
            else:
                cell.set_facecolor("white")
    except Exception as e:
        print(f"  Cluster table error: {e}")

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)

    # ── PAGE 6: Treatment Sequence & Chemo/Surgery Impact ─────────────────
    fig, axes = plt.subplots(2, 2, figsize=(12, 9))
    fig.suptitle("Treatment Sequence & Chemo/Surgery Impact", fontsize=13,
                 fontweight="bold", color=TITLE_COLOR, y=0.99)

    data_path = Path(__file__).parent.parent / "data/c15_enriched.csv"
    df6 = pd.read_csv(data_path, low_memory=False)
    df6["event"] = (df6["生存狀態(27)"].astype(str).str.strip()=="0").astype(int)
    df6["os_months"] = pd.to_numeric(df6["os_days"], errors="coerce") / 30.44

    STYPE = {"00":"No surgery","2E":"EMR/ESD","27":"Endoscopic","20":"Local excision",
             "30":"Partial esophagectomy","51":"Esophagectomy+recon","52":"Esophagogastrectomy",
             "53":"Esophagectomy+LND","54":"Radical esophagectomy","55":"Radical esoph+LND","99":"Unknown"}
    SGRP  = {"No surgery":"No surgery","EMR/ESD":"Endoscopic resection","Endoscopic":"Endoscopic resection",
             "Local excision":"Endoscopic resection","Partial esophagectomy":"Partial esophagectomy",
             "Esophagectomy+recon":"Radical esophagectomy","Esophagogastrectomy":"Radical esophagectomy",
             "Esophagectomy+LND":"Radical esophagectomy","Radical esophagectomy":"Radical esophagectomy",
             "Radical esoph+LND":"Radical esophagectomy","Unknown":"Unknown"}
    df6["surg_group"] = df6["原發部位手術方式(118)"].astype(str).str.strip().str.upper().map(STYPE).fillna("Unknown").map(SGRP).fillna("Unknown")
    op6 = df6[df6["surg_group"].isin(["Endoscopic resection","Partial esophagectomy","Radical esophagectomy"])].copy()
    rt_seq = pd.to_numeric(op6["放射治療與手術順序(140)"], errors="coerce")
    op6["seq_label"] = rt_seq.map({-7:"Neoadj CCRT→OP",-8:"Neoadj RT→OP",-1:"Neoadj chemo→OP",
                                    0:"OP only",1:"OP→adj chemo",4:"OP→adj RT",5:"OP→adj CCRT"}).fillna("Unknown")

    # A — Treatment sequence bar
    ax = axes[0,0]
    seq_order = ["Neoadj CCRT→OP","Neoadj RT→OP","Neoadj chemo→OP",
                 "OP only","OP→adj RT","OP→adj chemo","OP→adj CCRT"]
    seq_vc = op6["seq_label"].value_counts().reindex(seq_order).dropna()
    colors_seq = [ACCENT_COLOR if "Neoadj" in s else ("teal" if "only" in s else "steelblue") for s in seq_vc.index]
    ax.barh(seq_vc.index[::-1], seq_vc.values[::-1], color=colors_seq[::-1], edgecolor="white")
    for i,(v,s) in enumerate(zip(seq_vc.values[::-1], seq_vc.index[::-1])):
        ax.text(v+2, i, f"n={v}", va="center", fontsize=8)
    ax.set(title="A  Treatment Sequence (N=531 operated)", xlabel="Number of cases")
    ax.spines[["top","right"]].set_visible(False)

    # B — Surgery type donut
    ax = axes[0,1]
    surg_vc = op6["surg_group"].value_counts()
    wedge_colors_s = [ACCENT_COLOR, "steelblue", "teal"][:len(surg_vc)]
    wedges, _, autotexts = ax.pie(surg_vc, labels=None,
                                   autopct=lambda p: f"{p:.1f}%" if p > 3 else "",
                                   colors=wedge_colors_s, startangle=90,
                                   wedgeprops=dict(width=0.55, edgecolor="white"))
    for at in autotexts: at.set_fontsize(8)
    ax.legend([f"{k} (n={v})" for k,v in surg_vc.items()],
              loc="lower center", fontsize=7.5, ncol=1, frameon=True)
    ax.set_title("B  Surgery Type Distribution")

    # C — Sequence × Surgery type heatmap
    ax = axes[1,0]
    ct_mat = pd.crosstab(op6["seq_label"], op6["surg_group"]).reindex(
        [s for s in seq_order if s in op6["seq_label"].values]).fillna(0)
    ct_pct = ct_mat.div(ct_mat.sum(axis=1), axis=0)*100
    sns.heatmap(ct_pct, annot=ct_mat.astype(int), fmt="d", cmap="Blues",
                ax=ax, linewidths=0.4, cbar_kws={"label":"%"},
                annot_kws={"size":8})
    ax.set(title="C  Sequence × Surgery Type (n, % row)", xlabel="Surgery type",
           ylabel="Treatment sequence")
    ax.tick_params(axis="x", rotation=20, labelsize=7.5)
    ax.tick_params(axis="y", labelsize=7.5)

    # D — Chemo/surgery stats table
    ax = axes[1,1]
    ax.axis("off")
    stats_rows = [
        ["Metric", "Value"],
        ["Operated (any)", f"531 / 2,367 (22.4%)"],
        ["  Endoscopic resection", "180 (7.6%)"],
        ["  Partial esophagectomy", "17 (0.7%)"],
        ["  Radical esophagectomy", "334 (14.1%)"],
        ["Neoadjuvant → OP", "9 (1.7%)†"],
        ["  Neoadjuvant CCRT → OP", "8 (1.5%)"],
        ["OP only", "267 (50.3% of OP)"],
        ["OP → Adjuvant (any)", "255 (48.0% of OP)"],
        ["  OP → Adjuvant RT", "130 (24.5%)"],
        ["  OP → Adjuvant chemo", "103 (19.4%)"],
        ["  OP → Adjuvant CCRT", "22 (4.1%)"],
        ["CCRT (all patients)", "947 (40.0%)"],
        ["Chemo cycles available", "126 / 2,367 (5.3%)†"],
        ["RT dose available (Gy)", "1,179 / 2,367 (49.8%)"],
        ["Median RT dose", "50.4 Gy / 33 fractions"],
    ]
    tbl = ax.table(cellText=stats_rows[1:], colLabels=stats_rows[0],
                   loc="upper center", cellLoc="left",
                   bbox=[0, 0, 1, 1], colWidths=[0.65, 0.35])
    tbl.auto_set_font_size(False); tbl.set_fontsize(8)
    for (r,c),cell in tbl.get_celld().items():
        cell.set_edgecolor("#dddddd")
        if r==0:
            cell.set_facecolor(ACCENT_COLOR)
            cell.set_text_props(color="white", fontweight="bold")
        elif r%2==0: cell.set_facecolor("#eef4fb")
        else: cell.set_facecolor("white")
        if rows_content := stats_rows[r] if r < len(stats_rows) else None:
            pass
    ax.set_title("D  Treatment Summary Statistics", fontsize=9, color=TITLE_COLOR,
                 fontweight="bold", pad=4)
    fig.text(0.5, 0.01,
             "† Neoadjuvant rate (1.7%) likely underestimated: registry field captures RT-surgery "
             "relationship only. † Chemo cycles sparsely recorded (5.3%) — dose-response underpowered.",
             ha="center", fontsize=6.5, color=GRAY, style="italic")
    fig.tight_layout(rect=[0, 0.03, 1, 0.97])
    pdf.savefig(fig, dpi=150)
    plt.close(fig)


print(f"PDF saved: {OUT_PDF}")
